name: Build Docker Images

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          docuseal/docuseal
        tags: |
          type=semver,pattern={{version}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create .version file
      run: echo ${{ github.ref_name }} > .version

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
